all:
	g++ -g Archivator.cpp -Wall -Wextra -pedantic-errors -Wno-deprecated-declarations -std=c++17 -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG -o Archivator
	clang-format-7 -style=google -i Archivator.cpp
