all:
	g++ -g Terminal.cpp -Wall -Wextra -pedantic-errors -Wno-deprecated-declarations -std=c++17 -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG -o Terminal
	clang-format-7 -style=google -i Terminal.cpp
